version: '3.8'

services:
  apex-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: apex_retail_backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

  apex-edge:
    build:
      context: .
      dockerfile: Dockerfile.edge
    container_name: apex_retail_edge
    depends_on:
      - apex-backend
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://apex-backend:8000/api/live-events